#!/usr/bin/env bash
#
# Guardian force-install deployer for Ubuntu (Google Chrome).
#
# Installs:
#   1. Python FastAPI backend (systemd) — shared SQLite for all Chrome profiles
#   2. Packed/force-installed Chrome extension that talks to the backend
#   3. Parent LAN dashboard at http://<host>:8765
#
# Usage:
#   sudo ./deploy-guardian.sh
#
# Optional overrides (env vars):
#   SRC_DIR   = repo root                       (default: ~/Documents/Guardian)
#   EXT_DIR   = extension source folder         (default: $SRC_DIR/extension)
#   PEM       = signing key path                (default: ~/guardian.pem)
#   HOST_DIR  = where the crx is hosted         (default: /var/local/guardian-extension)
#   API_PORT  = backend listen port             (default: 8765)

set -euo pipefail

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME="$(getent passwd "$REAL_USER" | cut -d: -f6)"

SRC_DIR="${SRC_DIR:-$REAL_HOME/Documents/Guardian}"
EXT_DIR="${EXT_DIR:-$SRC_DIR/extension}"
PEM="${PEM:-$REAL_HOME/guardian.pem}"
HOST_DIR="${HOST_DIR:-/var/local/guardian-extension}"
POLICY_DIR="/etc/opt/chrome/policies/managed"
API_PORT="${API_PORT:-8765}"
BACKEND_DIR="/opt/guardian"
LOG_DIR="/var/local/guardian-logs"
TOKEN_FILE="/etc/guardian/extension_token"

echo "== Guardian deployer =="
echo "   user     : $REAL_USER"
echo "   source   : $SRC_DIR"
echo "   extension: $EXT_DIR"
echo "   key      : $PEM"
echo "   host dir : $HOST_DIR"
echo "   api port : $API_PORT"
echo

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run with sudo (sudo ./deploy-guardian.sh)" >&2
  exit 1
fi
if [[ ! -d "$EXT_DIR" ]]; then
  echo "ERROR: extension folder not found: $EXT_DIR" >&2
  exit 1
fi
if [[ ! -d "$SRC_DIR/backend" ]]; then
  echo "ERROR: backend folder not found: $SRC_DIR/backend" >&2
  exit 1
fi

CHROME_BIN="$(command -v google-chrome || command -v google-chrome-stable || true)"
if [[ -z "$CHROME_BIN" ]]; then
  echo "ERROR: google-chrome not found in PATH" >&2
  exit 1
fi

# --- Signing key ---
if [[ ! -f "$PEM" ]]; then
  echo ">> No key at $PEM — generating a new one (keep it safe!)"
  openssl genrsa 2048 > "$PEM"
  chown "$REAL_USER":"$REAL_USER" "$PEM"
  chmod 600 "$PEM"
fi

EXT_ID="$(openssl rsa -in "$PEM" -pubout -outform DER 2>/dev/null \
          | sha256sum | head -c 32 | tr 0-9a-f a-p)"
if [[ ${#EXT_ID} -ne 32 ]]; then
  echo "ERROR: failed to derive a 32-char extension ID from $PEM" >&2
  exit 1
fi
echo ">> Extension ID: $EXT_ID"

VERSION="$(grep -oP '"version"\s*:\s*"\K[0-9][0-9.]*' "$EXT_DIR/manifest.json" | head -1)"
VERSION="${VERSION:-2.0.0}"
echo ">> Extension version: $VERSION"

# --- Shared extension API token ---
mkdir -p /etc/guardian
if [[ ! -f "$TOKEN_FILE" ]]; then
  openssl rand -hex 24 > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
  echo ">> Generated new extension token at $TOKEN_FILE"
fi
EXT_TOKEN="$(tr -d '[:space:]' < "$TOKEN_FILE")"

# Write config.js into the extension before packing
cat > "$EXT_DIR/config.js" <<EOF
// Generated by deploy-guardian.sh — do not edit by hand on the device.
export const API_BASE = "http://127.0.0.1:${API_PORT}";
export const EXTENSION_TOKEN = "${EXT_TOKEN}";
EOF
echo ">> Wrote $EXT_DIR/config.js"

# Optional: seed parent PIN into the backend DB after service starts
SEED_PIN=""
read -rsp "Set parent PIN now (min 4 chars, blank to set later in the web UI): " PARENT_PIN
echo
if [[ -n "$PARENT_PIN" ]]; then
  if [[ ${#PARENT_PIN} -lt 4 ]]; then
    echo "ERROR: PIN must be at least 4 characters" >&2
    exit 1
  fi
  SEED_PIN="$PARENT_PIN"
fi

# --- Pack CRX ---
CRX_SRC="${EXT_DIR%/}.crx"
echo ">> Packing extension..."
sudo -u "$REAL_USER" "$CHROME_BIN" \
     --pack-extension="$EXT_DIR" \
     --pack-extension-key="$PEM" >/dev/null 2>&1 || true
if [[ ! -f "$CRX_SRC" ]]; then
  echo "ERROR: packing failed, $CRX_SRC not created" >&2
  exit 1
fi
echo "   packed: $CRX_SRC"

mkdir -p "$HOST_DIR"
cp -f "$CRX_SRC" "$HOST_DIR/Guardian.crx"

cat > "$HOST_DIR/update.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
  <app appid="$EXT_ID">
    <updatecheck codebase="file://$HOST_DIR/Guardian.crx" version="$VERSION" />
  </app>
</gupdate>
EOF

# --- Chrome policy (force-install Guardian; block installing any other extensions) ---
echo ">> Writing policy in $POLICY_DIR"
mkdir -p "$POLICY_DIR"
rm -f "$POLICY_DIR/guardian_force.json" "$POLICY_DIR/guardian.json" "$POLICY_DIR/disable_extensions.json"

# Discover already-installed extension IDs so they are allowlisted (kept),
# while "*" stays blocked for any NEW installs.
python3 - <<PY
import json, os, re
from pathlib import Path

policy_dir = Path("$POLICY_DIR")
ext_id = "$EXT_ID"
update_xml = "file://$HOST_DIR/update.xml"
# Only Guardian + AdBlock are permitted going forward.
adblock_id = "gighmmpiobklfepjocnamgkkbiglidom"
allowed = {ext_id, adblock_id}

ext_settings = {
    "*": {
        "installation_mode": "blocked",
        "blocked_install_message": "Installing extensions is disabled by parental controls.",
    },
    ext_id: {
        "installation_mode": "force_installed",
        "update_url": update_xml,
        "toolbar_pin": "force_pinned",
        # Prevent kids from revoking site access in chrome://extensions
        "runtime_allowed_hosts": ["*://*/*"],
        "runtime_blocked_hosts": [],
    },
    adblock_id: {
        "installation_mode": "normal_installed",
        "toolbar_pin": "force_pinned",
        "runtime_allowed_hosts": ["*://*/*"],
        "runtime_blocked_hosts": [],
    },
}

guardian = {
    "ExtensionInstallForcelist": [f"{ext_id};{update_xml}"],
    "ExtensionInstallSources": ["file:///*"],
    "ExtensionInstallBlocklist": ["*"],
    "ExtensionInstallAllowlist": sorted(allowed),
    "ExtensionSettings": ext_settings,
    "DeveloperToolsAvailability": 2,
    # Block creating new Chrome profiles / guest sessions
    "BrowserAddPersonEnabled": False,
    "BrowserGuestModeEnabled": False,
    "ProfilePickerOnStartupEnabled": False,
}
blocked = {
    "ExtensionInstallBlocklist": ["*"],
    "URLBlocklist": [
        "https://chromewebstore.google.com/*",
        "https://chrome.google.com/webstore/*",
        "chrome://extensions",
        "chrome://extensions/*",
    ],
}
profiles = {
    "BrowserAddPersonEnabled": False,
    "BrowserGuestModeEnabled": False,
    "ProfilePickerOnStartupEnabled": False,
}
(policy_dir / "guardian.json").write_text(json.dumps(guardian, indent=2) + "\\n")
(policy_dir / "blocked_extensions.json").write_text(json.dumps(blocked, indent=2) + "\\n")
(policy_dir / "block_profiles.json").write_text(json.dumps(profiles, indent=2) + "\\n")
print(">> Allowlisted extensions:", ", ".join(sorted(allowed)))
print(">> Guardian site access forced; chrome://extensions blocked")
print(">> New Chrome profiles / guest mode blocked")
PY

# --- Remove legacy native-messaging host if present ---
NM_HOST_NAME="com.guardian.logs"
NM_MANIFEST="/etc/opt/chrome/native-messaging-hosts/$NM_HOST_NAME.json"
if [[ -f "$NM_MANIFEST" ]]; then
  echo ">> Removing legacy native messaging host"
  rm -f "$NM_MANIFEST"
  rm -rf /opt/guardian-logs
fi

# --- Install Python backend + systemd unit ---
echo ">> Installing backend to $BACKEND_DIR"
mkdir -p "$BACKEND_DIR" "$LOG_DIR"
chmod 1777 "$LOG_DIR"

rsync -a --delete \
  --exclude 'data/' --exclude '__pycache__/' --exclude '.pytest_cache/' \
  --exclude 'tests/' \
  "$SRC_DIR/backend/" "$BACKEND_DIR/backend/"
cp -f "$SRC_DIR/backend/requirements.txt" "$BACKEND_DIR/requirements.txt"

python3 -m venv "$BACKEND_DIR/venv"
"$BACKEND_DIR/venv/bin/pip" install -q --upgrade pip
"$BACKEND_DIR/venv/bin/pip" install -q -r "$BACKEND_DIR/requirements.txt"

cat > /etc/guardian/backend.env <<EOF
GUARDIAN_HOST=0.0.0.0
GUARDIAN_PORT=$API_PORT
GUARDIAN_LOG_DIR=$LOG_DIR
GUARDIAN_DB_PATH=$LOG_DIR/guardian.db
GUARDIAN_EXTENSION_TOKEN=$EXT_TOKEN
GUARDIAN_SESSION_SECRET=$(openssl rand -hex 32)
EOF
chmod 600 /etc/guardian/backend.env

cat > /etc/systemd/system/guardian.service <<EOF
[Unit]
Description=Guardian parental-control backend
After=network.target

[Service]
Type=simple
EnvironmentFile=/etc/guardian/backend.env
WorkingDirectory=$BACKEND_DIR
ExecStart=$BACKEND_DIR/venv/bin/uvicorn backend.main:app --host 0.0.0.0 --port $API_PORT
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable guardian.service
systemctl restart guardian.service
sleep 1
if ! systemctl is-active --quiet guardian.service; then
  echo "ERROR: guardian.service failed to start" >&2
  systemctl status guardian.service --no-pager || true
  exit 1
fi
echo ">> Backend listening on 0.0.0.0:$API_PORT"

if [[ -n "$SEED_PIN" ]]; then
  echo ">> Seeding parent PIN via API..."
  curl -sS -X POST "http://127.0.0.1:$API_PORT/api/auth/setup" \
    -H "Content-Type: application/json" \
    -d "{\"pin\":\"$SEED_PIN\",\"confirm\":\"$SEED_PIN\"}" >/dev/null || true
fi

LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
LAN_IP="${LAN_IP:-<this-pc-ip>}"

chown -R root:root /etc/opt/chrome/policies "$HOST_DIR" /etc/guardian
chmod 644 "$POLICY_DIR"/*.json
chmod -R a+rX "$HOST_DIR"

echo
echo "== Done =="
echo "   Policy     : $POLICY_DIR/guardian.json"
echo "   Host       : $HOST_DIR (Guardian.crx + update.xml)"
echo "   Backend    : guardian.service (db: $LOG_DIR/guardian.db)"
echo "   Dashboard  : http://$LAN_IP:$API_PORT  (any device on the LAN)"
echo "   Local URL  : http://127.0.0.1:$API_PORT"
echo "   Ext ID     : $EXT_ID"
echo
echo "Logs from every Chrome profile on this PC go into one shared database."

echo
echo ">> Stopping Chrome for all users..."
pkill -f chrome 2>/dev/null || true
sleep 2

STALE_IDS=(
  "odlameecjipmbmbejkplpemijjgpljcea"
  "nkhamemnhgfepknbkogoneejfegfonam"
  "$EXT_ID"
)
echo ">> Cleaning old extension installs from all Chrome profiles..."
shopt -s nullglob
for home in /home/* /root; do
  cfg="$home/.config/google-chrome"
  [[ -d "$cfg" ]] || continue
  for extroot in "$cfg"/*/Extensions; do
    [[ -d "$extroot" ]] || continue
    for id in "${STALE_IDS[@]}"; do
      if [[ -d "$extroot/$id" ]]; then
        rm -rf "$extroot/$id"
        echo "   removed $extroot/$id"
      fi
    done
  done
done
shopt -u nullglob

echo
echo ">> Restarting Chrome..."
sudo -u "$REAL_USER" nohup "$CHROME_BIN" >/dev/null 2>&1 &

echo
echo "Next: open chrome://policy -> Reload policies, and confirm"
echo "ExtensionInstallForcelist shows $EXT_ID with status OK."
echo "Parents: open http://$LAN_IP:$API_PORT from a phone/PC on the same network."
